### ISSUE TITLE
How do you approach a competition ? What is your pipeline generally like ?

### ISSUE THREAD

**Issue by pulkitmehtawork** [jeongyoonlee/kaggler-tv#4]

**Comment by jeongyoonlee** [comment]
Hi @pulkitmehtawork, I just uploaded the demo video showing my pipeline based on [kaggler-template](https://github.com/jeongyoonolee/kaggler-template). Please check it out. :)

**Comment by pulkitmehtawork** [comment]
Thanks a lot ... I will definitely check it .. You are guiding and providing lot of good quality content .
