### ISSUE TITLE
Kaggle Task Video

### ISSUE THREAD

**Issue by kgilpas** [jeongyoonlee/kaggler-tv#5]
Hi thanks for the channel! 

On content request perhaps in the future there could be a video walking through a Kaggle Task or even a showcase of completing a Kaggle task using your pipelines or  CausalML library.

Thank you very much.

**Comment by jeongyoonlee** [comment]
uploaded a video on how to manage code & tasks at Kaggle competition: https://youtu.be/HqhG7T9UL88
